const layoutWidget = {
    // 元数据
    metadata: {
        name: 'Web4 Layout',
        version: '1.0.0',
        description: 'Main layout component for Web4 applications'
    },

    // HTML 模板
    html: [
        '<div class="layout-container">',
        '    <div class="theme-toggle">',
        '        <button id="themeToggle" aria-label="Toggle theme">',
        '            <svg class="sun-icon" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">',
        '                <circle cx="12" cy="12" r="5"></circle>',
        '                <line x1="12" y1="1" x2="12" y2="3"></line>',
        '                <line x1="12" y1="21" x2="12" y2="23"></line>',
        '                <line x1="4.22" y1="4.22" x2="5.64" y2="5.64"></line>',
        '                <line x1="18.36" y1="18.36" x2="19.78" y2="19.78"></line>',
        '                <line x1="1" y1="12" x2="3" y2="12"></line>',
        '                <line x1="21" y1="12" x2="23" y2="12"></line>',
        '                <line x1="4.22" y1="19.78" x2="5.64" y2="18.36"></line>',
        '                <line x1="18.36" y1="5.64" x2="19.78" y2="4.22"></line>',
        '            </svg>',
        '            <svg class="moon-icon" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">',
        '                <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path>',
        '            </svg>',
        '        </button>',
        '    </div>',
        '    <div class="background-decoration"></div>',
        '    <div id="title-container"></div>',
        '    <div id="main-container"></div>',
        '</div>'
    ].join('\n'),

    // CSS 样式
    css: [
        '@import url(\'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&display=swap\');',
        '',
        ':root {',
        '    --bg-light: #ffffff;',
        '    --bg-dark: #0a0b14;',
        '    --text-light: #1a1a1a;',
        '    --text-dark: #ffffff;',
        '    --accent: #6366f1;',
        '    --accent-hover: #4f46e5;',
        '    --border-light: #e2e8f0;',
        '    --border-dark: rgba(255, 255, 255, 0.1);',
        '    --transition: 0.3s cubic-bezier(0.4, 0, 0.2, 1);',
        '}',
        '',
        'body {',
        '    margin: 0;',
        '    padding: 0;',
        '    background: var(--bg-dark);',
        '    color: var(--text-dark);',
        '    font-family: \'Space Grotesk\', system-ui, -apple-system, sans-serif;',
        '    transition: background var(--transition), color var(--transition);',
        '    min-height: 100vh;',
        '}',
        '',
        'body.light-theme {',
        '    background: var(--bg-light);',
        '    color: var(--text-light);',
        '}',
        '',
        '.layout-container {',
        '    max-width: 1200px;',
        '    margin: 0 auto;',
        '    padding: 20px;',
        '    min-height: 100vh;',
        '    position: relative;',
        '}',
        '',
        '.theme-toggle {',
        '    position: fixed;',
        '    top: 20px;',
        '    right: 20px;',
        '    z-index: 1000;',
        '}',
        '',
        '.theme-toggle button {',
        '    background: rgba(18, 20, 26, 0.9);',
        '    border: 1px solid var(--border-dark);',
        '    cursor: pointer;',
        '    padding: 10px;',
        '    border-radius: 50%;',
        '    color: white;',
        '    width: 44px;',
        '    height: 44px;',
        '    display: flex;',
        '    align-items: center;',
        '    justify-content: center;',
        '    transition: all var(--transition);',
        '    backdrop-filter: blur(10px);',
        '}',
        '',
        '.light-theme .theme-toggle button {',
        '    background: rgba(255, 255, 255, 0.9);',
        '    border-color: var(--border-light);',
        '    color: var(--text-light);',
        '}',
        '',
        '.theme-toggle button:hover {',
        '    transform: scale(1.1);',
        '    background: var(--accent);',
        '    border-color: var(--accent);',
        '    color: white;',
        '}',
        '',
        '.sun-icon { display: none; }',
        '.moon-icon { display: block; }',
        '.light-theme .sun-icon { display: block; }',
        '.light-theme .moon-icon { display: none; }',
        '',
        '.background-decoration {',
        '    position: fixed;',
        '    top: 0;',
        '    left: 0;',
        '    width: 100%;',
        '    height: 100%;',
        '    z-index: -1;',
        '    background: ',
        '        radial-gradient(circle at 20% 30%, rgba(99, 102, 241, 0.1) 0%, transparent 50%),',
        '        radial-gradient(circle at 80% 70%, rgba(139, 92, 246, 0.1) 0%, transparent 50%);',
        '    transition: opacity var(--transition);',
        '}',
        '',
        '#main-container {',
        '    margin-top: 40px;',
        '}'
    ].join('\n'),

    // JavaScript 逻辑
    js: [
        '// Theme toggle',
        'function initTheme() {',
        '    const toggle = document.getElementById(\'themeToggle\');',
        '    const savedTheme = localStorage.getItem(\'theme\');',
        '    ',
        '    if (savedTheme === \'light\') {',
        '        document.body.classList.add(\'light-theme\');',
        '    }',
        '',
        '    toggle.addEventListener(\'click\', () => {',
        '        document.body.classList.toggle(\'light-theme\');',
        '        const isLight = document.body.classList.contains(\'light-theme\');',
        '        localStorage.setItem(\'theme\', isLight ? \'light\' : \'dark\');',
        '    });',
        '}',
        '',
        '// Load widget by transaction ID directly',
        'async function loadWidgetById(containerId, txid) {',
        '    try {',
        '        console.log(`Loading widget from: ${txid}`);',
        '        const response = await fetch(`https://gateway.irys.xyz/${txid}`);',
        '        if (!response.ok) throw new Error(`HTTP ${response.status}`);',
        '        const widget = await response.json();',
        '        if (typeof window.applyWidget === \'function\') {',
        '            window.applyWidget(containerId, widget);',
        '            console.log(`✅ Widget loaded: ${containerId}`);',
        '        }',
        '    } catch (error) {',
        '        console.error(`Failed to load widget ${containerId}:`, error);',
        '    }',
        '}',
        '',
        '// Initialize',
        'async function initLayout() {',
        '    initTheme();',
        '    ',
        '    // Load widgets by transaction ID',
        '    await loadWidgetById(\'title-container\', \'DXu2cryGiJ2UuvTjWuz4oJZJBeonERwVVJx498ErbUmW\');',
        '}',
        '',
        'if (document.readyState === \'loading\') {',
        '    document.addEventListener(\'DOMContentLoaded\', initLayout);',
        '} else {',
        '    initLayout();',
        '}'
    ].join('\n')
};

module.exports = { layoutWidget };
